config/routes.rb
LunchOptimizer::Application.routes.draw do
  resources :lunches do
    member do
      put :attend
      put :unattend
      get :rank
    end
  end

  resources :categories

  resources :restaurants

  devise_for :users

  resources :groups do
    resources :lunches
    member do
      put  :quit
      put  :join
    end
  end

  match 'joinbycode(/:code)' => 'groups#joinbycode', :as => 'joinbycode', :defaults => { :code => nil }
  get 'ratings' => 'rating#index'
  post 'ratings' => 'rating#set'
  get 'history' => 'history#index'
  get 'history/:year/:month' => 'history#month'
  get 'history/:year/:month/:day' => 'history#edit'
  post 'history/update' => 'history#update'

  root :to => "home#index"

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => "users_groups"
  has_and_belongs_to_many :restaurants
  has_and_belongs_to_many :lunches, :join_table => "lunches_groups"
  has_many :hosted_lunches, :class_name => 'Lunch', :foreign_key => 'host_group_id'
  belongs_to :owner, :class_name => 'User', :foreign_key => 'owner_id'
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.xml
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.xml
  def show
    @group = Group.find(params[:id], :include => :restaurants)
    @restaurants = 
      (Group.find :all,
        :include => [:restaurants, :users], :conditions => ['groups.id = ?',@group.id.to_s])
      .collect{|g| g.restaurants}.flatten.uniq.collect do |restaurant|
        rating = restaurant.ratings.where(:user_id => current_user, :end_date => nil).first
        {:restaurant => restaurant, :rating => (rating.nil? ? 50 : rating.rating)}
      end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.xml
  def new
    @group = Group.new
    @restaurants = Restaurant.all(:order => 'name').collect { |r| [r.name, r.id] }

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @restaurants = Restaurant.all(:order => 'name').collect { |r| [r.name, r.id] }
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.xml
  def create
    @group = Group.new(params[:group])
    @group.owner = current_user

    respond_to do |format|
      if @group.save
        format.html { redirect_to(@group, :notice => 'Group was successfully created.') }
        format.xml  { render :xml => @group, :status => :created, :location => @group }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.xml
  def update
    @group = Group.find(params[:id])
    if @group.owner == current_user
      respond_to do |format|
        if @group.update_attributes(params[:group])
          format.html { redirect_to(@group, :notice => 'Group was successfully updated.') }
          format.xml  { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.xml
  def destroy
    @group = Group.find(params[:id])
    if @group.owner == current_user
      @group.destroy

      respond_to do |format|
        format.html { redirect_to(groups_url) }
        format.xml  { head :ok }
      end
    end
  end

  # PUT /groups/join/1
  def join
    #TODO Eventually we'll probably check permissions here
    @group = Group.find(params[:id])
    respond_to do |format|
      if current_user.groups.include? @group
        # Do nothing, we're already in
        format.js { render :text => 'Failed' }
      else
        current_user.groups << @group
        format.js { render :text => 'Success' }
      end
    end
  end

  # PUT /groups/quit/1
  def quit
    #TODO Eventually we'll probably check permissions here
    @group = Group.find(params[:id])
    respond_to do |format|
      if current_user.groups.include? @group
        current_user.groups.delete @group
        format.js { render :text => 'Success' }
      else
        # Do nothing, we're not in anyways
        format.js { render :text => 'Failed' }
      end
    end
  end

  # POST /groups/joinbycode/PAREXPEDIA
  def joinbycode
    code = if params[:code].nil? then params[:code_form] else params[:code] end
    if not code.nil? then
      @group = Group.where("lower(code) = lower(:code)", { :code => code}).first
      if not @group.nil? then
        if not current_user.groups.include? @group then
					current_user.groups << @group
					flash[:notice] = 'Added to group "'+@group.name+'".'
				else
					flash[:error] = 'Already in group.'
				end
      else
				flash[:error] = 'No groups found with this code.'
      end
    end
  end

end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= form_for @group do |f|
  -if @group.errors.any?
    #error_explanation
      %h2= "#{pluralize(@group.errors.count, "error")} prohibited this group from being saved:"
      %ul
        - @group.errors.full_messages.each do |msg|
          %li= msg

  .input
    = f.label :name
    = f.text_field :name
  .input
    = f.label :code
    = f.text_field :code
  .input
    = f.label :description
    = f.text_area :description
  .input
    = f.label :restaurant_ids
    = f.select :restaurant_ids, options_for_select(@restaurants, @group.restaurant_ids), {}, { :class => 'chzn-select', :multiple => true }
  .input
    = f.label :default_longitude
    = f.text_field :default_longitude
  .input
    = f.label :default_latitude
    = f.text_field :default_latitude
  .submit
    = f.submit 'Save'

app/views/groups/edit.html.haml
-content_for :header do
  %h1
    =image_tag "icons/users.png"
    Editing group
.bloc
  .title
    Edit Group
  .content
    =render 'form'

= link_to 'Show', @group
\|
= link_to 'Back', groups_path

app/views/groups/index.html.haml
-content_for :head do
  :javascript
    $(function(){
      $('.join-button')
        .bind("ajax:complete", function(){
          $(this).siblings('.quit-button').toggle();
          $(this).toggle();
          var members = $(this).parent().siblings('.members');
          members.text(parseInt(members.text())+1);
        });
      $('.quit-button')
        .bind("ajax:complete", function(){
          $(this).toggle();
          $(this).siblings('.join-button').toggle();
          var members = $(this).parent().siblings('.members');
          members.text(parseInt(members.text())-1);
        });
    });
-content_for :header do
  %h1
    =image_tag "icons/users.png"
    Groups
.bloc
  .title
    Groups
  .content
    %p
      This is a listing of all groups in the system. Likely you'll want to 
      =link_to "search", "#"
      for a group instead, or simply 
      =link_to "enter their code", joinbycode_path
      \. If you don't find a group that you like, 
      =link_to 'create a new group', new_group_path
      \.
    %table
      %thead
        %tr
          %th
            %input.checkall(type="checkbox")
          %th
            Name
          %th
            Code
          %th
            Members
          %th
      %tbody
        -@groups.each do |group|
          %tr
            %td
              %input(type="checkbox")
            %td=link_to group.name, group
            %td=group.code
            %td.members=group.users.count
            %td
              =link_to "Quit", quit_group_path(group), :method => 'put', :remote => true, :class => 'black quit-button button', :style => ((current_user.groups.include? group) ? "" : "display: none;")
              =link_to "Join", join_group_path(group), :method => 'put', :remote => true, :class => 'white join-button button', :style => ((current_user.groups.include? group) ? "display: none;" : "")
              -if group.owner == current_user
                =link_to 'Edit', edit_group_path(group), :class => 'button'
                =link_to 'Delete', group, :confirm => 'Are you sure?', :method => :delete, :class => 'button'

app/views/groups/joinbycode.html.haml
-content_for :header do
  %h1
    =image_tag "icons/users.png"
    Groups
.bloc
  .title
    Join by Code
  .content
    %p
      Enter the code of the group you'd like to join below. If you don't know the code of the group you'd like join then you can
      =link_to 'search for them', groups_path
      \.
    =form_tag do
      .input
        =label_tag :code_form
        =text_field_tag :code_form
      .submit
        =submit_tag 'Join'

app/views/groups/new.html.haml
%h1
  =image_tag "icons/users.png"
  New group

.bloc
  .title
    New Group
  .content
    =render 'form'

= link_to 'Back', groups_path

app/views/groups/show.html.haml
-content_for :head do
  :javascript
    var single_user = #{(@group.users.count == 0 || (@group.users.count == 1 && (@group.users.include? current_user))).to_s};
    $(function(){
      $('.join-button')
        .bind("ajax:complete", function(){
          $('.display-lunches').toggle();
          $('.hidden-lunches').toggle();
          $(this).siblings('.quit-button').toggle();
          $(this).toggle();
          $('.me').toggle();
          if(single_user){
            $('.no-members').toggle();
            $('.yes-members').toggle();
          }
        });
      $('.quit-button')
        .bind("ajax:complete", function(){
          $('.display-lunches').toggle();
          $('.hidden-lunches').toggle();
          $(this).toggle();
          $(this).siblings('.join-button').toggle();
          $('.me').toggle();
          if(single_user){
            $('.no-members').toggle();
            $('.yes-members').toggle();
          }
        });
    });
-content_for :header do
  %h1
    =image_tag "icons/users.png"
    =@group.name 
.bloc.left
  .title
    Group Information
  .content
    .center
      %p
        %b Code:
        = @group.code
      %p
        %b Description:
        = @group.description
      %p
        %b Default longitude:
        = @group.default_longitude
      %p
        %b Default latitude:
        = @group.default_latitude

      -if @group.owner == current_user
        = link_to 'Edit', edit_group_path(@group), :class => 'button'
      =link_to "Join", join_group_path(@group), :method => 'put', :remote => true, :class => 'white button join-button', :style => ((current_user.groups.include? @group) ? "display: none;" : "")
      =link_to "Quit", quit_group_path(@group), :method => 'put', :remote => true, :class => 'black button quit-button', :style => ((current_user.groups.include? @group) ? "" : "display: none;")
.bloc.right
  .title
    Map
  .content.center
    %img{:src => "http://maps.googleapis.com/maps/api/staticmap?center="+@group.default_longitude.to_s+','+@group.default_latitude.to_s+"&zoom=14&size=300x300&maptype=hybrid&sensor=false&markers=color:blue%7C"+@group.default_longitude.to_s+','+@group.default_latitude.to_s}
.bloc.left
  .title
    Upcoming Lunches
  .content
    .display-lunches{:style => ((current_user.groups.include? @group) ? "" : "display: none;")}
      -if @group.lunches.count == 0
        None currently, 
        =link_to "start one", new_group_lunch_path(@group)
        \!
      -else
        %ul
          -@group.lunches.order(:date).where(['date > NOW()']).each do |lunch|
            %li
              =link_to @lunch, "#{lunch.name} (#{lunch.formatted_date})"
        =link_to "Start a lunch", new_group_lunch_path(@group)
    .hidden-lunches{:style => ((not current_user.groups.include? @group) ? "" : "display: none;")}
      %p
        You can't see the lunches this group is going to until you join!
.cb
.bloc
  .title
    Members
  .content
    .center
      -if @group.users.count == 0 || (@group.users.count == 1 && (@group.users.include? current_user))
        %p.no-members{:style => ((@group.users.count == 0) ? "" : "display: none;")}
          No members currently.
      %ul.yes-members{:style => ((@group.users.count == 0) ? "display: none;" : "")}
        %li.me{:style => ((current_user.groups.include? @group) ? "" : "display: none;")}
          %strong=current_user.email
        -@group.users.each do |user|
          -if current_user.id != user.id
            %li=user.email
=render 'rating/block'