config/routes.rb
LunchOptimizer::Application.routes.draw do
  resources :lunches do
    member do
      put :attend
      put :unattend
      get :rank
    end
  end

  resources :categories

  resources :restaurants

  devise_for :users

  resources :groups do
    resources :lunches
    member do
      put  :quit
      put  :join
    end
  end

  match 'joinbycode(/:code)' => 'groups#joinbycode', :as => 'joinbycode', :defaults => { :code => nil }
  get 'ratings' => 'rating#index'
  post 'ratings' => 'rating#set'
  get 'history' => 'history#index'
  get 'history/:year/:month' => 'history#month'
  get 'history/:year/:month/:day' => 'history#edit'
  post 'history/update' => 'history#update'

  root :to => "home#index"

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :ratings
  has_and_belongs_to_many :categories, :join_table => 'restaurants_categories'
  has_and_belongs_to_many :groups
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # GET /restaurants
  # GET /restaurants.xml
  def index
    @restaurants = Restaurant.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @restaurants }
    end
  end

  # GET /restaurants/1
  # GET /restaurants/1.xml
  def show
    @restaurant = Restaurant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @restaurant }
    end
  end

  # GET /restaurants/new
  # GET /restaurants/new.xml
  def new
    @restaurant = Restaurant.new
    @categories = Category.all(:order => 'name').collect { |cat| [cat.name, cat.id] }

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @restaurant }
    end
  end

  # GET /restaurants/1/edit
  def edit
    @restaurant = Restaurant.find(params[:id])
    #@restaurant.category_ids = @restaurant.categories.collect { |cat| [cat.name, cat.id] }
    @categories = Category.all.collect { |cat| [cat.name, cat.id] }
  end

  # POST /restaurants
  # POST /restaurants.xml
  def create
    @restaurant = Restaurant.new(params[:restaurant])

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to(@restaurant, :notice => 'Restaurant was successfully created.') }
        format.xml  { render :xml => @restaurant, :status => :created, :location => @restaurant }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @restaurant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /restaurants/1
  # PUT /restaurants/1.xml
  def update
    @restaurant = Restaurant.find(params[:id])

    respond_to do |format|
      if @restaurant.update_attributes(params[:restaurant])
        format.html { redirect_to(@restaurant, :notice => 'Restaurant was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @restaurant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.xml
  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    respond_to do |format|
      format.html { redirect_to(restaurants_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.haml
= form_for @restaurant do |f|
  -if @restaurant.errors.any?
    #error_explanation
      %h2= "#{pluralize(@restaurant.errors.count, "error")} prohibited this restaurant from being saved:"
      %ul
        - @restaurant.errors.full_messages.each do |msg|
          %li= msg
  .input
    = f.label :name
    = f.text_field :name
  .input
    = f.label :category_ids
    = f.select :category_ids, options_for_select(@categories), {}, { :class => 'chzn-select', :multiple => true }
  .input
    = f.label :link
    = f.text_field :link
  .input
    = f.label :latitude
    = f.text_field :latitude
  .input
    = f.label :longitude
    = f.text_field :longitude
  .input
    = f.label :description
    = f.text_area :description
  .submit
    = f.submit 'Save'

app/views/restaurants/edit.html.haml
%h1 Editing restaurant

= render 'form'

= link_to 'Show', @restaurant
\|
= link_to 'Back', restaurants_path

app/views/restaurants/index.html.haml
-content_for :header do
  %h1
    =image_tag "icons/document-checklist.png"
    Restaurants

.bloc
  .title
    Restaurants
  .content
    %table
      %thead
        %tr
          %th Name
          %th Description
          %th Link
          %th

      %tbody
        - @restaurants.each do |restaurant|
          %tr
            %td= link_to(restaurant.name,restaurant)
            %td= restaurant.description
            %td= restaurant.link
            %td
              = link_to image_tag('icons/actions/edit.png'), edit_restaurant_path(restaurant)
              = link_to image_tag('icons/actions/delete.png'), restaurant, :confirm => 'Are you sure?', :method => :delete

    %p
      =link_to 'New Restaurant', new_restaurant_path

app/views/restaurants/new.html.haml
-content_for :header do 
  %h1
    =image_tag 'icons/button-burn.png'
    New restaurant
.bloc
  .title
    New Restaurant
  .content
    =render 'form'

app/views/restaurants/show.html.haml
-content_for :header do
  %h1
    =image_tag "icons/document-checklist.png"
    Restaurants
.bloc
  .title
    =@restaurant.name
  .content
    %p#notice= notice
    %p
      %b Latitude:
      = @restaurant.latitude
    %p
      %b Longitude:
      = @restaurant.longitude
    %p
      %b Description:
      = @restaurant.description
    %p
      %b Link:
      = @restaurant.link
    %p
      %b Categories:
      = @restaurant.categories.map {|c| c.name}.join(', ')

= link_to 'Edit', edit_restaurant_path(@restaurant)
\|
= link_to 'Back', restaurants_path