config/routes.rb
LunchOptimizer::Application.routes.draw do
  resources :lunches do
    member do
      put :attend
      put :unattend
      get :rank
    end
  end

  resources :categories

  resources :restaurants

  devise_for :users

  resources :groups do
    resources :lunches
    member do
      put  :quit
      put  :join
    end
  end

  match 'joinbycode(/:code)' => 'groups#joinbycode', :as => 'joinbycode', :defaults => { :code => nil }
  get 'ratings' => 'rating#index'
  post 'ratings' => 'rating#set'
  get 'history' => 'history#index'
  get 'history/:year/:month' => 'history#month'
  get 'history/:year/:month/:day' => 'history#edit'
  post 'history/update' => 'history#update'

  root :to => "home#index"

end

app/models/lunch.rb
class Lunch < ActiveRecord::Base
  validates_presence_of :date, :name
  validates_uniqueness_of :name

  belongs_to :host_group, :class_name => 'Group', :foreign_key => 'host_group_id'
  belongs_to :host_user, :class_name => 'User', :foreign_key => 'host_user_id'
  has_and_belongs_to_many :groups, :join_table => "lunches_groups"
  has_and_belongs_to_many :users, :join_table => 'users_lunches'

  def formatted_date
    date.strftime('%m/%d/%Y')
  end

  def formatted_date=(date_str)
    self.date = DateTime.strptime(date_str, '%m/%d/%Y')
  end
end

app/controllers/lunches_controller.rb
class LunchesController < ApplicationController
  # GET /lunches
  # GET /lunches.xml
  def index
    if params[:group_id].nil?
      @lunches = Lunch.all
    else
      @group = Group.find(params[:group_id])
      @lunches = @group.lunches
    end

    respond_to do |format|
      unless params.include? :bare
        format.html
      else
        format.html { render :layout => 'bare' }
      end
      format.xml  { render :xml => @lunches }
    end
  end

  # GET /lunches/1
  # GET /lunches/1.xml
  def show
    @lunch = Lunch.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @lunch }
    end
  end

  # Setup private variables for the groups and restaurants
  def setup_groups_and_restaurants
    @restaurants = Restaurant.all(:order => 'name').collect { |r| [r.name, r.id] }
    @restaurants.unshift ['*Optimized', -1]
    @groups = current_user.groups(:order => 'name').collect { |g| [g.name, g.id]}
  end

  # GET /lunches/new
  # GET /lunches/new.xml
  # GET /groups/1/lunches/new
  def new
    @lunch = Lunch.new(
      :restaurant_id => -1,
      :date => DateTime.now,
      :host_user => current_user,
      :host_group => current_user.groups.first,
      :name => "Lunch #{DateTime.now.strftime("%m-%d-%y")}"
    )
    @lunch.host_group = Group.find(params[:group_id]) unless params[:group_id].nil?
    setup_groups_and_restaurants

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @lunch }
    end
  end

  # GET /lunches/1/edit
  def edit
    @lunch = Lunch.find(params[:id])
    setup_groups_and_restaurants
  end

  # POST /lunches
  # POST /lunches.xml
  def create
    @lunch = Lunch.new(params[:lunch])
    host_group = Group.find(@lunch.host_group_id)
    @lunch.groups << host_group unless @lunch.groups.include? host_group
    @lunch.users << current_user
    @lunch.host_user = current_user
    setup_groups_and_restaurants

    respond_to do |format|
      if @lunch.save
        format.html { redirect_to(@lunch, :notice => 'Lunch was successfully created.') }
        format.xml  { render :xml => @lunch, :status => :created, :location => @lunch }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @lunch.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /lunches/1
  # PUT /lunches/1.xml
  def update
    @lunch = Lunch.find(params[:id])
    setup_groups_and_restaurants

    respond_to do |format|
      if @lunch.update_attributes(params[:lunch])
        format.html { redirect_to(@lunch, :notice => 'Lunch was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @lunch.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /lunches/join/1
  def attend
    #TODO Eventually we'll probably check permissions here
    @lunch = Lunch.find(params[:id])
    respond_to do |format|
      if current_user.lunches.include? @lunch
        # Do nothing, we're already in
        format.js { render :text => 'Failed' }
      else
        current_user.lunches << @lunch
        format.js { render :text => 'Success' }
      end
    end
  end

  # PUT /lunches/quit/1
  def unattend
    #TODO Eventually we'll probably check permissions here
    @lunch = Lunch.find(params[:id])
    respond_to do |format|
      if current_user.lunches.include? @lunch
        current_user.lunches.delete @lunch
        format.js { render :text => 'Success' }
      else
        # Do nothing, we're not in anyways
        format.js { render :text => 'Failed' }
      end
    end
  end

  # GET /lunches/rank/1
  def rank
    @lunch = Lunch.find(params[:id])    

    respond_to do |format|
      format.xml { render :xml => @rankings }
    end
  end

  # DELETE /lunches/1
  # DELETE /lunches/1.xml
  def destroy
    @lunch = Lunch.find(params[:id])
    @lunch.destroy

    respond_to do |format|
      format.html { redirect_to(lunches_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/lunches_helper.rb
module LunchesHelper
  # Returns {:name, :id, :rank} of ALL restaurants included in the host group
  def rank(lunch)
    restaurants = lunch.host_group.restaurants
    users = lunch.users
    base_rank = restaurants.collect do |restaurant|
      { :name => restaurant.name,
        :id => restaurant.id,
        :rank => 1
      }
    end
    
  end

  def historical_falloff

  end

  def history_summary(users,restaurants)
    # Need something like...

  end
end

app/views/lunches/_form.html.haml
= form_for @lunch do |f|
  -if @lunch.errors.any?
    #error_explanation
      %h2= "#{pluralize(@lunch.errors.count, "error")} prohibited this lunch from being saved:"
      %ul
        - @lunch.errors.full_messages.each do |msg|
          %li= msg

  .form-column
    .input
      %label
        Hosts
      %p
        %em=@lunch.host_user.email
      %p
        The person responsible for calling the restaurant in advance if necessary and herding the cats when the time comes.
    .input
      = f.label :name
      %p
        A unique name for this lunch.
      = f.text_field :name
    .input
      = f.label :date
      %p
        The date the lunch occurs
      = f.text_field :formatted_date, :class => 'datepicker'
  .form-column
    .input
      =f.label :host_group
      =f.select :host_group_id, options_for_select(@groups, @lunch.host_group_id), {}, {:class => 'chzn-select'}
      %p
        This group decides what restaurants will be included and is invited by default
    .input
      = f.label :restaurant_id
      %p
        For special occasions, lunch destinations can be fixed.
      = f.select :restaurant_id, options_for_select(@restaurants, @lunch.restaurant_id), {}, {:class => 'chzn-select' }
    .input
      = f.label :group_id
      %p
        These are the groups that will be invited and able to join this lunch. You must be a member to invite the group.
      = f.select :group_ids, options_for_select(@groups, @lunch.group_ids), {}, {:class => 'chzn-select', :multiple => 'true' }
  .cb
  .submit
    = f.submit 'Save'

app/views/lunches/edit.html.haml
-content_for :header do
  %h1
    =image_tag "icons/lunch.png"
    Lunch
.bloc
  .title
    Editing Lunch
  .content
    =render 'form'
    =link_to 'Show', @lunch

app/views/lunches/index.html.haml
.bloc
  .title
    Lunches
  .content
    %p
      Listed below are all the lunches that you've created or are attended.
    %table
      %thead
        %tr
          %th Name
          %th Date
          %th Groups
          %th Restaurant
          %th

      %tbody
        - @lunches.each do |lunch|
          %tr
            %td= lunch.name
            %td= lunch.date
            %td= lunch.group_ids
            %td= lunch.restaurant_id
            %td
              = link_to 'Show', lunch
              = link_to 'Edit', edit_lunch_path(lunch)
              = link_to 'Destroy', lunch, :confirm => 'Are you sure?', :method => :delete

    %p= link_to 'New Lunch', new_lunch_path

app/views/lunches/new.html.haml
-content_for :header do
  %h1
    =image_tag "icons/lunch.png"
    Lunch
.bloc
  .title
    New Lunch
  .content
    =render 'form'

app/views/lunches/show.html.haml
-content_for :head do
  :javascript
    var single_user = #{(@lunch.users.count == 0 || (@lunch.users.count == 1 && (@lunch.users.include? current_user))).to_s};
    $(function(){
      $('.join-button')
        .bind("ajax:complete", function(){
          $(this).siblings('.quit-button').toggle();
          $(this).toggle();
          $('.me').toggle();
          if(single_user){
            $('.no-attendees').toggle();
            $('.yes-attendees').toggle();
          }
        });
      $('.quit-button')
        .bind("ajax:complete", function(){
          $(this).toggle();
          $(this).siblings('.join-button').toggle();
          $('.me').toggle();
          if(single_user){
            $('.no-attendees').toggle();
            $('.yes-attendees').toggle();
          }
        });
    });
-content_for :header do
  %h1
    =image_tag "icons/lunch.png"
    Lunch
.bloc
  .title
    =@lunch.name
  .content
    %p
      %b Name:
      = @lunch.name
    %p
      %b Date:
      = @lunch.date
    %p
      %b Group:
      = @lunch.group_ids
    %p
      %b Restaurant:
      = @lunch.restaurant_id
    = link_to 'Edit', edit_lunch_path(@lunch), :class => 'button'
    =link_to "I'm Attending", attend_lunch_path(@lunch), :method => 'put', :remote => true, :class => 'white button join-button', :style => ((@lunch.users.include? current_user) ? "display: none;" : "")
    =link_to "I'm Not Attending", unattend_lunch_path(@lunch), :method => 'put', :remote => true, :class => 'black button quit-button', :style => ((@lunch.users.include? current_user) ? "" : "display: none;")
.bloc
  .title
    Attendees
  .content
    -if @lunch.users.count == 0 || (@lunch.users.count == 1 && (@lunch.users.include? current_user))
      %p.no-attendees{:style => ((@lunch.users.count == 0) ? "" : "display: none;")}
        No attendees currently.
    %ul.yes-attendees{:style => ((@lunch.users.count == 0) ? "display: none;" : "")}
      %li.me{:style => ((current_user.lunches.include? @lunch) ? "" : "display: none;")}
        %strong=current_user.email
      -@lunch.users.each do |user|
        -if current_user.id != user.id
          %li=user.email