config/routes.rb
LunchOptimizer::Application.routes.draw do
  resources :lunches do
    member do
      put :attend
      put :unattend
      get :rank
    end
  end

  resources :categories

  resources :restaurants

  devise_for :users

  resources :groups do
    resources :lunches
    member do
      put  :quit
      put  :join
    end
  end

  match 'joinbycode(/:code)' => 'groups#joinbycode', :as => 'joinbycode', :defaults => { :code => nil }
  get 'ratings' => 'rating#index'
  post 'ratings' => 'rating#set'
  get 'history' => 'history#index'
  get 'history/:year/:month' => 'history#month'
  get 'history/:year/:month/:day' => 'history#edit'
  post 'history/update' => 'history#update'

  root :to => "home#index"

end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title LunchOptimizer
    = stylesheet_link_tag 'reset.css'
    
    -# Main stylesheed  (EDIT THIS ONE) -->
    = stylesheet_link_tag 'style.css'
    
    -# jQuery AND jQueryUI -->
    = javascript_include_tag 'jquery.min.js'
    = javascript_include_tag 'jquery-ui.min.js'
    = stylesheet_link_tag 'jqueryui/jqueryui.css'
    
    -# jWysiwyg - https://github.com/akzhan/jwysiwyg/ -->
    -#= stylesheet_link_tag 'jwysiwyg/jquery.wysiwyg.old-school.css'
    -#= javascript_include_tag 'jwysiwyg/jquery.wysiwyg.js'
    
    
    -# Tooltipsy - http://tooltipsy.com/ -->
    = javascript_include_tag 'tooltipsy.min.js'
    
    -# iPhone checkboxes - http://awardwinningfjords.com/2009/06/16/iphone-style-checkboxes.html -->
    = javascript_include_tag 'iphone-style-checkboxes.js'
    = javascript_include_tag 'excanvas.js'
    
    -# Load zoombox (lightbox effect) - http://www.grafikart.fr/zoombox -->
    = javascript_include_tag 'zoombox.js'
    = stylesheet_link_tag 'zoombox.css'
    
    -# Charts - http://www.filamentgroup.com/lab/update_to_jquery_visualize_accessible_charts_with_html5_from_designing_with/ -->
    = javascript_include_tag 'visualize.jQuery.js'
    
    -# Uniform - http://uniformjs.com/ -->
    = javascript_include_tag 'jquery.uniform.min.js'

    -# JQuery UJS
    = javascript_include_tag 'jquery_ujs.js'

    -# Chosen Select
    -# javascript_include_tag 'chosen.jquery.min.js'
    = javascript_include_tag 'chosen.jquery.js'
    = stylesheet_link_tag 'chosen.css'
    
    
    -# Main Javascript that do the magic part (EDIT THIS ONE) -->
    = javascript_include_tag 'application.js'

    = stylesheet_link_tag 'all.css'

    = csrf_meta_tag

    :javascript
      $(function(){
        $(".chzn-select").chosen() 
        $("a.zoombox").zoombox({
          animation: false,
          theme: 'lightbox'
        });
      });
    =yield :head
  %body.dark
    -if user_signed_in?
      #head
        .left
          %a.button.profile(href="")
            =image_tag "icons/top/huser.png"
          Hi,
          %a(href="#")
            =current_user.email
          | 
          =link_to 'Sign Out', destroy_user_session_path, :method => 'delete'
        .right
          ="3,230 lunches served."
      #logo
        =image_tag "small.png"
      #sidebar
        %ul
          %li.nosubmenu
            =link_to image_tag("icons/menu/home.png")+' Home', :controller => 'home'
          %li.current
            %a(href="#")
              =image_tag "icons/menu/inbox2.png"
              Main
            %ul
              %li
                =link_to 'History', history_path
              %li
                =link_to 'Groups', groups_path
              %li
                =link_to 'Categories', categories_path
              %li
                =link_to 'Restaurants', restaurants_path
              %li
                =link_to 'Ratings', ratings_path
              %li
                =link_to 'Lunches', lunches_path
          %li
            %a(href="#")
              =image_tag "icons/menu/shirt.png"
              Groups
            %ul
              %li
                =link_to "Join a Group", groups_path
                %a(href="#")
                  Start a Group
                -@menu_groups.each do |group|
                  %a.generated{:href => url_for(group)}
                    =group.name
          %li.nosubmenu
            %a.zoombox.w450.h400(href="lunches?bare")
              Modal
      #content.white
        =yield :header
        -if flash[:notice]
          .notif.info.bloc
            %strong
              Notice :
            =flash[:notice]
            %a.close(href="#")
        -if flash[:error]
          .notif.error.bloc
            %strong
              Error :
            =flash[:error]
            %a.close(href="#")
        =yield
    -else
      =yield :header
      -if flash[:notice]
        .notif.info.bloc
          %strong
            Notice :
          =flash[:notice]
          %a.close(href="#")
      -if flash[:error]
        .notif.error.bloc
          %strong
            Error :
          =flash[:error]
          %a.close(href="#")
      =yield

app/views/layouts/bare.html.haml
!!! 5
%html
  %head
    = stylesheet_link_tag 'reset.css'
    = stylesheet_link_tag 'style.css'
    = stylesheet_link_tag 'jqueryui/jqueryui.css'
    = stylesheet_link_tag 'chosen.css'
    = stylesheet_link_tag 'all.css'
  %body.dark
  #content.white
    =yield